#
###################################
# Site wide configuration
####################################
#
title:       "A blog of Edoardo Causarano"
description: "I'm a software developer, mostly proficient in Java but weaning off OO to properly practice software design (that would be Functional Programming)"
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Amsterdam
markdown:          kramdown
highlighter:       rogue
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Edoardo
  avatar:  IMG_3873.png
  job: "Java Developer"
  bio: "I'm a software developer, mostly proficient in Java but weaning off OO to properly practice software design (that would be Functional Programming)"
  email: edoardo . causarano@gmail.com
  disqus-shortname: causarano
  google:
    plus: #username
    analytics: UA-73129001-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ecausarano #username
  stackoverflow: 261984/eddy 
  linkedin: ecausarano
