#
###################################
# Site wide configuration
####################################
#
title:       "A blog of Edoardo Causarano"
description: "Notes and humblebrags"
url:        http://www.causarano.eu 

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Amsterdam
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Edoardo
  avatar:  IMG_3873.png
  job: "Engineer and Software Developer"
  bio: "Somewhat polyglot programmer I tend to steer toward Functional Programming designs" 
  email: edoardo . causarano@gmail.com
  # disqus-shortname: causarano
  google:
    plus: #username
    analytics: UA-73129001-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ecausarano #username
  stackoverflow: 261984/eddy 
  linkedin: ecausarano
